---
title: "Diversity and Connection"
author: "DHP"
date: "January 11, 2019"
output: githug_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lattice)
library(ggplot2)
library(tidyverse)
dflmer <- readRDS("NEW_DEC18/Tables/dflmer_w.rds")
dflmer$EPTRichness <- dflmer$GastRichness + dflmer$PlecRichness + dflmer$TRichRichness 
dflmer$fstat <- factor(paste(dflmer$station, dflmer$site))
str(dflmer)

tab_long_orders <- gather(dflmer, key = order, value = richness, c(5:10,21))

f_brut_o <- tab_long_orders %>% 
  filter(order %in% c("EPTRichness", "GastRichness")) %>% 
  ggplot(aes(Overflow, richness,color = season))
f_brut_f1 <- tab_long_orders %>% 
  filter(order %in% c("EPTRichness", "GastRichness")) %>% 
  ggplot(aes(F1, richness,color = season))
f_log_o <- tab_long_orders %>% 
  filter(order %in% c("EPTRichness", "GastRichness")) %>% 
  ggplot(aes(log(Overflow+1), richness,color = season))


f_brut_o + geom_point() + facet_wrap(vars(order)) 
f_log_o + geom_point() + facet_wrap(vars(order)) 
f_brut_f1 + geom_point() + facet_wrap(vars(order))

```



```{r}
library(lme4)

names(dflmer)
m1 <- lm(GastRichness ~ log(Overflow+1)+season, data=dflmer)


mm1 <-  lmer(GastRichness ~ Overflow + season + (1|station), data=dflmer, REML = F)
mm1_1 <-  lmer(GastRichness ~ F1 + season + (1|station), data=dflmer, REML = F)
mm1_2 <-  lmer(GastRichness ~ log(Overflow+1) + season + (1|station), data=dflmer, REML = F)

mm2 <-  lmer(EPTRichness ~ Overflow + season + (1|station), data=dflmer, REML = F)
mm2_1 <-  lmer(EPTRichness ~ F1 + season + (1|station), data=dflmer, REML = F)
mm2_2 <-  lmer(EPTRichness ~ log(Overflow+1) + season + (1|station), data=dflmer, REML = F)


anova(mm1,mm1_1, mm1_2)
anova(mm2,mm2_1, mm2_2)

AIC(mm1,mm1_1, mm1_2)
AIC(mm2,mm2_1, mm2_2)


```

